### ISSUE TITLE
STIX version

### ISSUE THREAD

**Issue by sashabel** [stucco/STIXExtractors#1]
Hi, 
I have a couple questions :
-  what version of stix do you support ?
- do you use ML algorithms or only NLP ? 
- In case you use ML, is there a tagged set of documents you train the model on ?

**Comment by MariaVincent** [comment]
Hi,

- We used STIX 1.2 version
- We used only NLP

**Comment by jgoodall** [comment]
Regarding bullet's  2&3 : Presumably the question means "are you using only unsupervised NLP techniques, or more standard supervised machine learning techniques for classifying entities in text". 

Our techniques are described in publications, all available for download from https://sites.google.com/site/robertbridgeshomepage/ (right column under "NLP + Cyber Papers").
 
Our training corpus is available here: 
https://github.com/stucco/auto-labeled-corpus

**Comment by mikeiannacone** [comment]
Also, I should point out that the actual NLP code is in the `relation-extractor` and `entity-extractor` repos, and those steps are done earlier in the document processing.  In this repo, the `StuccoExtractor` class handles the output from those NLP steps, but everything else in this repo is dealing with well-structured sources (which don't need the NLP.)

Hope that helps!

**Comment by sashabel** [comment]
thanks . it did help

**Comment by hanozo** [comment]
Hey mike,
In regards to your previous comment. You'd mentioned "relation-extractor and entity-extractor repos, and those steps are done earlier in the document processing". So I conducted "entity-extractor" on a document of mine and got the annotation object that represents the document as a map. And I wonder how this object model can be used as STIXExtractors input?
Is there any repro in which such a document processing pipeline can be found?

Thank you.
 Hanozo

**Comment by mikeiannacone** [comment]
Sure thing.  The `rt` repo contains the main worker process, and the `UnstructuredTransformer` class in that repo handles all of the unstructured text & NLP.  

Specifically, this is where the entity labeling begins:
https://github.com/stucco/rt/blob/9b8dbe8d13618d55b7f6a7797b1f7a60c067e49c/streaming-processor/src/main/java/gov/ornl/stucco/unstructured/UnstructuredTransformer.java#L163

After that, the relations are labeled, and it's transformed into STIX.  (More specifically, it is a STIX-based graph representation which is only used internally.  Everything that would be exposed to a user is normal STIX, however.)  The relations are found with the `relationExtractor.createSubgraph(...)` call on L175, and its output is passed to a `StuccoExtractor` constructor, which creates the STIX-graph.

Finally, it's handed off to `alignment`, which handles de-duplication and related tasks, and inserts it into the database.  That is done by the `alignment.load(graph)` call here:
https://github.com/stucco/rt/blob/9b8dbe8d13618d55b7f6a7797b1f7a60c067e49c/streaming-processor/src/main/java/gov/ornl/stucco/unstructured/UnstructuredTransformer.java#L183

Most of the rest of the `UnstructuredTransformer` class is handling various initialization tasks, handling messages from the queue, and similar tasks.

Hope that helps!
